name: movies

services:
  pg:
    image: bitnami/postgresql
    ports:
      - "7007:5432"
    environment:
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: movies
    volumes:
      - pg-data:/var/lib/postgresql/pg-data
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ports:
      - "4433:6379"
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    command: ["--proactor_threads=4", "--maxmemory=1gb"]

volumes:
   pg-data:
   dragonflydata:
   minio-data:
